### PR TITLE
Tooltip attempt

### PR DESCRIPTION
**Pull request by edmundmok**
Shows only what is necessary

### CODE REVIEW

**Comment by edmundmok** [comment]
Tooltip works by substring now (from any index). Alternative is to match starting from the beginning of the string only.

**Comment by linhany** [comment]
Looks good to me. So we can enable the travis thing after merging this?

**Review by linhany — APPROVED** [review]

**Comment by edmundmok** [comment]
Not sure how that works

**Comment by linhany** [comment]
I will do it after this is merged

**Pull request merged**
