### PR TITLE
Reduce size of everything and remove footer bar

### PR DESCRIPTION
**Pull request by linhany**
@edmundmok Try it out & merge if ok.

### CODE REVIEW

**Comment by edmundmok** [comment]
not sure about this the font looks dam small. plus I increased the font size cause that time michelle said the tooltip font was too small

**Comment by linhany** [comment]
Yeah its quite small, but have to find a way cos the current ui u can only have like 3 todos lol. Cant see the big picture. If you dogfood it u will realise

**Comment by edmundmok** [comment]
i only catfood it didnt realize

**Comment by linhany** [comment]
seriously tho, i would prefer the original view where the dates are at the right then. there is no pt for the app to be small size if u cant see more than 4 tasks

**Pull request closed without merging**
